### ISSUE TITLE
RE3 version

### ISSUE THREAD

**Issue by JOHN30011887** [TheTedder/REFix#21]
Just tested this out and it works perfect for the zombie framerates, no more laggy zombies, great work :D

But was wondering if its possible for a RE3 version please, if its being worked on or know of any fix that works out there, 
i havnt found/seen anything that works with the new Ray Tracing dx12 versions

**Comment by SaulsaDip** [comment]
Seconded. Just tried this out on the DX12 RT updated version and it works flawlessly. Finally, a fix for the mouse acceleration and zombie framerates!

This unfortunately does not work on RE3R, and it's such a shame because it makes that game much harder to play after using this fix in RE2R and makes it the only RE Engine Resident Evil game with unfixed mouse acceleration.

As a very minor nitpick, I would also separate the dynamic difficulty removal as this is more of a subjective fix than an objective one like mouse input or zombie framerates.

**Comment by hyperspeedgx** [comment]
> I hit the close issue button by accident. I'm such a klutz. RE3 version might be a thing in the future but I don't have time at the moment to dedicate to it. Settings for the individual features of the mod are also planned (see #16).

Looking foward to the RE3 version of this, thanks again. 👍
